catalogMode: prefer
ignoreWorkspaceRootCheck: true
shamefullyHoist: true
shellEmulator: true
trustPolicy: no-downgrade
trustPolicyExclude:
  - vite@6.4.1

packages:
  - packages/*

catalogs:
  dev:
    '@astrojs/check': ^0.9.6
    '@astrojs/vue': ^5.1.4
    '@ycs77/eslint-config': ^7.0.0
    astro: ^5.16.11
    bumpp: ^10.4.0
    chokidar: ^5.0.0
    eslint: ^9.39.2
    eslint-plugin-astro: ^1.5.0
    eslint-plugin-astro-explicit-wrapper: ^1.0.5
    npm-run-all2: ^8.0.4
    semver: ^7.7.3
    tsdown: ^0.19.0
    typescript: ^5.9.3
    vitest: ^4.0.17
    vue: ^3.5.27
  prod:
    '@graphql-typed-document-node/core': ^3.2.0
    awesome-graphql-client: ^2.1.0
    graphql: ^16.12.0
    graphql-tag: ^2.12.6
    nanostores: ^1.1.0
    query-string: ^9.3.1

onlyBuiltDependencies:
  - esbuild
  - sharp
